// JavaScript Document
// 機械的に生成しない部分のツリー構造を出力します。
// node_ で始まるクラスは各HTMLページのbodyのクラスに対応します。

document.open();

var text = ""
+ '<div class="section">'
+ '  <div class="title node_introduction"><span class="arrow"></span><a href="introduction.html">はじめに</a></div>'
+ '  <div class="content">'
+ '    <ul>'
+ '      <li><a href="introduction.html#1">機能・特徴</a></li>'
+ '      <li><a href="introduction.html#2">動作環境</a></li>'
+ '      <li><a href="introduction.html#3">素材規格</a></li>'
+ '      <li><a href="introduction.html#4">利用規約</a></li>'
+ '      <li><a href="introduction.html#5">プログラムフォルダー構造</a></li>'
+ '      <li><a href="introduction.html#6">プロジェクトフォルダー構造</a></li>'
+ '      <li><a href="introduction.html#7">ライブラリ権利情報</a></li>'
+ '    </ul>'
+ '  </div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_editor"><span class="arrow"></span><a href="editor.html">エディター部</a></div>'
+ '  <div class="content">'

+ '    <div class="section">'
+ '      <div class="title node_editor-menu"><span class="arrow"></span><a href="editor-menu.html">上部メニュー</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="editor-menu.html#1">プロジェクト</a></li>'
+ '          <li><a href="editor-menu.html#2">表示</a></li>'
+ '          <li><a href="editor-menu.html#3">ツール</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <div class="section">'
+ '      <div class="title node_editor-schedule"><span class="arrow"></span><a href="editor-schedule.html">スケジュール</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="editor-schedule.html#1">ビューア</a></li>'
+ '          <li><a href="editor-schedule.html#2">エディター</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <div class="section">'
+ '      <div class="title node_editor-text"><span class="arrow"></span><a href="editor-text.html">テキスト エディター</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="editor-text.html#1">ファイルツリー</a></li>'
+ '          <li><a href="editor-text.html#2">支援機能サイドバー</a></li>'
+ '          <li><a href="editor-text.html#3">編集ツール</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <div class="section">'
+ '      <div class="title node_editor-database"><span class="arrow"></span><a href="editor-database.html">データベース エディター</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="editor-database.html#1">全般</a></li>'
+ '          <li><a href="editor-database.html#2">DB: システム</a></li>'
+ '          <li><a href="editor-database.html#3">DB: 初期設定</a></li>'
+ '          <li><a href="editor-database.html#4">DB: パーティキャラ</a></li>'
+ '          <li><a href="editor-database.html#5">DB: クラス</a></li>'
+ '          <li><a href="editor-database.html#6">DB: スキル</a></li>'
+ '          <li><a href="editor-database.html#7">DB: アイテム</a></li>'
+ '          <li><a href="editor-database.html#8">DB: 間接効果</a></li>'
+ '          <li><a href="editor-database.html#9">DB: エネミー</a></li>'
+ '          <li><a href="editor-database.html#10">DB: ユニット</a></li>'
+ '          <li><a href="editor-database.html#11">DB: エフェクト</a></li>'
+ '          <li><a href="editor-database.html#12">DB: タイルセット</a></li>'
+ '          <li><a href="editor-database.html#13">DB: 汎用素材</a></li>'
+ '          <li><a href="editor-database.html#14">DB: 変数/フラグ</a></li>'
+ '          <li><a href="editor-database.html#15">DB: 基本要素</a></li>'
+ '          <li><a href="editor-database.html#16">DB: ユーザー定義</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <div class="section">'
+ '      <div class="title node_editor-map"><span class="arrow"></span><a href="editor-map.html">マップ エディター</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="editor-map.html#1">マップの基本構造</a></li>'
+ '          <li><a href="editor-map.html#2">ファイルツリー</a></li>'
+ '          <li><a href="editor-map.html#3">レイヤー</a></li>'
+ '          <li><a href="editor-map.html#4">タイルパレット</a></li>'
+ '          <li><a href="editor-map.html#5">デザイナー</a></li>'
+ '          <li><a href="editor-map.html#6">イベント編集</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <ul>'
+ '      <li><a href="editor.html#6">細かい動作仕様</a></li>'
+ '    </ul>'
+ '  </div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_game"><span class="arrow"></span><a href="game.html">ゲームプログラム部</a></div>'
+ '  <div class="content">'

+ '    <div class="section">'
+ '      <div class="title node_game-knowledge"><span class="arrow"></span><a href="game-knowledge.html">基本概念</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="game-knowledge.html#1">大まかな処理の流れ</a></li>'
+ '          <li><a href="game-knowledge.html#2">主要機能アクセスツリー</a></li>'
+ '          <li><a href="game-knowledge.html#3">フレームレート</a></li>'
+ '          <li><a href="game-knowledge.html#4">DXライブラリ</a></li>'
+ '          <li><a href="game-knowledge.html#5">疑似マルチスレッド機構</a></li>'
+ '          <li><a href="game-knowledge.html#6">データベース</a></li>'
+ '          <li><a href="game-knowledge.html#7">各種素材</a></li>'
+ '          <li><a href="game-knowledge.html#8">スプライト</a></li>'
+ '          <li><a href="game-knowledge.html#9">セーブ・ロード</a></li>'
+ '          <li><a href="game-knowledge.html#10">カレントシーン</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <ul>'
+ '      <li><a href="game.html#2">スクリプトとの連携</a></li>'
+ '      <li><a href="game.html#3">ゲーム操作方法</a></li>'
+ '      <li><a href="game.html#4">デバッグ</a></li>'
+ '      <li><a href="game.html#5">細かい動作仕様</a></li>'
+ '    </ul>'
+ '  </div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_sq"><span class="arrow"></span><a href="sq.html">スクリプト言語「Squirrel」</a></div>'
+ '  <div class="content">'
+ '    <ul>'
+ '      <li><a href="sq.html#1">基本概念</a></li>'
+ '    </ul>'

+ '    <div class="section">'
+ '      <div class="title node_sq-syntax"><span class="arrow"></span><a href="sq-syntax.html">基本文法</a></div>'
+ '      <div class="content">'
+ '        <ul>'
+ '          <li><a href="sq-syntax.html#1">字句構造</a></li>'
+ '          <li><a href="sq-syntax.html#2">変数・定数・プロパティ</a></li>'
+ '          <li><a href="sq-syntax.html#3">基本データ型</a></li>'
+ '          <li><a href="sq-syntax.html#4">演算子</a></li>'
+ '          <li><a href="sq-syntax.html#5">テーブル</a></li>'
+ '          <li><a href="sq-syntax.html#6">配列</a></li>'
+ '          <li><a href="sq-syntax.html#7">制御文</a></li>'
+ '          <li><a href="sq-syntax.html#8">関数</a></li>'
+ '          <li><a href="sq-syntax.html#9">クラス</a></li>'
+ '        </ul>'
+ '      </div>'
+ '    </div>'

+ '    <ul>'
+ '      <li><a href="sq.html#3">注意すべき点</a></li>'
+ '    </ul>'
+ '  </div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_preset"><span class="arrow"></span><a href="preset.html">標準スクリプト仕様</a></div>'
+ '  <div class="content">'
+ '    <ul>'
+ '      <li><a href="preset.html#1">汎用機能</a></li>'
+ '      <li><a href="preset.html#2">イベントハンドラー</a></li>'
+ '      <li><a href="preset.html#3">ユーザーデータベース</a></li>'
+ '      <li><a href="preset.html#4">タイトルシーン</a></li>'
+ '      <li><a href="preset.html#5">マップシーン</a></li>'
+ '      <li><a href="preset.html#6">メニューシーン</a></li>'
+ '      <li><a href="preset.html#7">ショップシーン</a></li>'
+ '      <li><a href="preset.html#8">バトルシーン</a></li>'
+ '    </ul>'
+ '  </div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_guide"><span class="arrow"></span><a href="guide.html">RPG製作ガイド</a></div>'
+ '  <div class="content">'
+ '    <ul>'
+ '      <li><a href="guide.html#1">作り始める前に</a></li>'
+ '      <li><a href="guide.html#2">グループで作る場合</a></li>'
+ '      <li><a href="guide.html#3">スケジュールを立てる</a></li>'
+ '      <li><a href="guide.html#4">シナリオを固める</a></li>'
+ '      <li><a href="guide.html#5">スクリプトコーディング</a></li>'
+ '      <li><a href="guide.html#6">データベース打ち込み</a></li>'
+ '      <li><a href="guide.html#7">マップの製作</a></li>'
+ '      <li><a href="guide.html#8">マップイベントの作成</a></li>'
+ '      <li><a href="guide.html#9">テストプレイ</a></li>'
+ '      <li><a href="guide.html#10">リリース</a></li>'
+ '    </ul>'
+ '  </div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_releasenote"><span class="non-arrow"></span><a href="releasenote.html">更新履歴</a></div>'
+ '</div>'

+ '<div class="section">'
+ '  <div class="title node_qa"><span class="non-arrow"></span><a href="qa.html">よくある質問</a></div>'
+ '</div>'

;

document.write(text);
document.close();
