//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   RPG Developer NEXT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Autorun]
        ///open=Game.exe
        ///icon=icon.ico
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string autorun {
            get {
                return ResourceManager.GetString("autorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Code_Comment1 {
            get {
                return ResourceManager.GetString("Code_Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   */ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Code_CommentEnd {
            get {
                return ResourceManager.GetString("Code_CommentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Code_CommentStart {
            get {
                return ResourceManager.GetString("Code_CommentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (なし) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DB_NoneItem {
            get {
                return ResourceManager.GetString("DB_NoneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //効果音とともにアニメーションする
        ///Game.DB.FDBMaterial.Play($2, 255, 0, 0);
        ///Game.SceneMap.MapData.ThisEVData
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Direction, Direction4.East, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Direction, Direction4.North, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Direction, Direction4.West, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.NoHit, TRUE, &quot;&quot;)
        ///	.DoEx [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //効果音とともにアニメーションする
        ///Game.DB.FDBMaterial.Play($2, 255, 0, 0);
        ///Game.SceneMap.MapData.ThisEVData
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Direction, Direction4.West, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Direction, Direction4.South, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Direction, Direction4.North, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///	.SetExtraMove(EventMoveTask.NoHit, TRUE, &quot;&quot;)
        ///	.DoE [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoorLink {
            get {
                return ResourceManager.GetString("DoorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //鍵の所持確認
        ///if(Game.DB.VDBParty.CheckItemInParty($1)) {
        ///	//効果音とともにアニメーションする
        ///	Game.DB.FDBMaterial.Play($2, 255, 0, 0);
        ///	Game.SceneMap.MapData.ThisEVData
        ///		.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Direction, Direction4.West, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Direction, Direction4.South, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Wait, 50, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Direction, Direction4.North, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Wa [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoorLinkWithKey {
            get {
                return ResourceManager.GetString("DoorLinkWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //鍵の所持確認
        ///if(Game.DB.VDBParty.CheckItemInParty($1)) {
        ///	//効果音とともにアニメーションする
        ///	Game.DB.FDBMaterial.Play($2, 255, 0, 0);
        ///	Game.SceneMap.MapData.ThisEVData
        ///		.SetExtraMove(EventMoveTask.Wait, 100, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Direction, Direction4.East, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Wait, 100, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Direction, Direction4.North, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Wait, 100, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask.Direction, Direction4.West, &quot;&quot;)
        ///		.SetExtraMove(EventMoveTask. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoorWithKey {
            get {
                return ResourceManager.GetString("DoorWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_DB {
            get {
                return ResourceManager.GetString("Extension_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .ttf;.ttc;.otf;.ttf;.fon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_Font {
            get {
                return ResourceManager.GetString("Extension_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .png;.bmp;.jpg;.dds;.argb;.tga に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_Graphics {
            get {
                return ResourceManager.GetString("Extension_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .mp3;.wav;.ogg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_LoopSounds {
            get {
                return ResourceManager.GetString("Extension_LoopSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_Map {
            get {
                return ResourceManager.GetString("Extension_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .eds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_ProjectSystemFile {
            get {
                return ResourceManager.GetString("Extension_ProjectSystemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .mid;.mp3;.wav;.ogg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_Sounds {
            get {
                return ResourceManager.GetString("Extension_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_SQ {
            get {
                return ResourceManager.GetString("Extension_SQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .sqt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_SQTemplate {
            get {
                return ResourceManager.GetString("Extension_SQTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .tile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension_Tileset {
            get {
                return ResourceManager.GetString("Extension_Tileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイル (*.jpg;*.png;*.bmp)|*.jpg;*.png;*.bmp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter_Graphics {
            get {
                return ResourceManager.GetString("Filter_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.75 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form_TeamSplitRate {
            get {
                return ResourceManager.GetString("Form_TeamSplitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon icon_editor {
            get {
                object obj = ResourceManager.GetObject("icon_editor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon icon_gameprogram {
            get {
                object obj = ResourceManager.GetObject("icon_gameprogram", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   ライセンス情報：
        ///アイコン：赤まぐろ（小樽商科大学）
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.ChangeMap($1, $2, $3, $4);
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザーが編集しているため、ファイルを操作できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_AcccessError {
            get {
                return ResourceManager.GetString("MsgE_AcccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_Cannot {
            get {
                return ResourceManager.GetString("MsgE_Cannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_Failed {
            get {
                return ResourceManager.GetString("MsgE_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同名の$が既に存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_FileExists {
            get {
                return ResourceManager.GetString("MsgE_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効な$名です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_FileNameInvarid {
            get {
                return ResourceManager.GetString("MsgE_FileNameInvarid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $を重複させることはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_ForbidOverlap {
            get {
                return ResourceManager.GetString("MsgE_ForbidOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたフォルダーは正しいプロジェクトフォルダーではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_InvaridPrj {
            get {
                return ResourceManager.GetString("MsgE_InvaridPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムフォルダー/ファイルは$できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_NGDeleteRoot {
            get {
                return ResourceManager.GetString("MsgE_NGDeleteRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $が設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_NothingInput {
            get {
                return ResourceManager.GetString("MsgE_NothingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジャンプリストに該当する行頭文字列が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_NothingJumpList {
            get {
                return ResourceManager.GetString("MsgE_NothingJumpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_NothingSelect {
            get {
                return ResourceManager.GetString("MsgE_NothingSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取り専用モードのため、保存操作は行えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgE_ReadOnly {
            get {
                return ResourceManager.GetString("MsgE_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終端まで置換しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgI_CompleteTextReplace {
            get {
                return ResourceManager.GetString("MsgI_CompleteTextReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgQ_Confirm {
            get {
                return ResourceManager.GetString("MsgQ_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中の$を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgQ_Save {
            get {
                return ResourceManager.GetString("MsgQ_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgW_ImportantWork {
            get {
                return ResourceManager.GetString("MsgW_ImportantWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在他のユーザーによって編集されているため、閲覧モードで開きます。編集結果は保存できませんのでご注意下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgW_ReadOnly {
            get {
                return ResourceManager.GetString("MsgW_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中にエラーが発生しました。操作が完全に行われていない可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgW_ResultError {
            get {
                return ResourceManager.GetString("MsgW_ResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .db;.ini に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NG_FileExtension {
            get {
                return ResourceManager.GetString("NG_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ,;&quot;| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NG_String {
            get {
                return ResourceManager.GetString("NG_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NG_SystemFolderSymbol {
            get {
                return ResourceManager.GetString("NG_SystemFolderSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_ArchiveData {
            get {
                return ResourceManager.GetString("Path_ArchiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs {
            get {
                return ResourceManager.GetString("Path_DBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Char.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Char {
            get {
                return ResourceManager.GetString("Path_DBs_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Class.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Class {
            get {
                return ResourceManager.GetString("Path_DBs_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Effect.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Effect {
            get {
                return ResourceManager.GetString("Path_DBs_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\$Effects\$Top.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_EffectScriptCenter {
            get {
                return ResourceManager.GetString("Path_DBs_EffectScriptCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\$Effects\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_EffectScripts {
            get {
                return ResourceManager.GetString("Path_DBs_EffectScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Element.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Element {
            get {
                return ResourceManager.GetString("Path_DBs_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Enemy.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Enemy {
            get {
                return ResourceManager.GetString("Path_DBs_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Init.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Init {
            get {
                return ResourceManager.GetString("Path_DBs_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Item.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Item {
            get {
                return ResourceManager.GetString("Path_DBs_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Material.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Material {
            get {
                return ResourceManager.GetString("Path_DBs_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Skill.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Skill {
            get {
                return ResourceManager.GetString("Path_DBs_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\State.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_State {
            get {
                return ResourceManager.GetString("Path_DBs_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\System.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_System {
            get {
                return ResourceManager.GetString("Path_DBs_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Tileset.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Tileset {
            get {
                return ResourceManager.GetString("Path_DBs_Tileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\$Tilesets\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Tilesets {
            get {
                return ResourceManager.GetString("Path_DBs_Tilesets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Unit.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Unit {
            get {
                return ResourceManager.GetString("Path_DBs_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\UserDB.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_UserDB {
            get {
                return ResourceManager.GetString("Path_DBs_UserDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\$UserDatabases\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_UserDBs {
            get {
                return ResourceManager.GetString("Path_DBs_UserDBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databases\Value.tsv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_DBs_Value {
            get {
                return ResourceManager.GetString("Path_DBs_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fonts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Fonts {
            get {
                return ResourceManager.GetString("Path_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_GameProgram {
            get {
                return ResourceManager.GetString("Path_GameProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game_Release.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_GameProgramRelease {
            get {
                return ResourceManager.GetString("Path_GameProgramRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GuruGuruSMF4.dll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_GGS {
            get {
                return ResourceManager.GetString("Path_GGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual\index.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Manual {
            get {
                return ResourceManager.GetString("Path_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maps\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Maps {
            get {
                return ResourceManager.GetString("Path_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Materials\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Materials {
            get {
                return ResourceManager.GetString("Path_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PresetData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_PresetData {
            get {
                return ResourceManager.GetString("Path_PresetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $ProjectSystem\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_PrjSys {
            get {
                return ResourceManager.GetString("Path_PrjSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $ProjectSystem\EVTemplates\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_PrjSys_EVTemplate {
            get {
                return ResourceManager.GetString("Path_PrjSys_EVTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $ProjectSystem\Project.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_PrjSys_PrjFile {
            get {
                return ResourceManager.GetString("Path_PrjSys_PrjFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $ProjectSystem\Schedule.eds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_PrjSys_ScheduleFile {
            get {
                return ResourceManager.GetString("Path_PrjSys_ScheduleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts {
            get {
                return ResourceManager.GetString("Path_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBChar.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Char {
            get {
                return ResourceManager.GetString("Path_Scripts_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBClass.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Class {
            get {
                return ResourceManager.GetString("Path_Scripts_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$Constants.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Constants {
            get {
                return ResourceManager.GetString("Path_Scripts_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBEnemy.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Enemy {
            get {
                return ResourceManager.GetString("Path_Scripts_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$Functions.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Functions {
            get {
                return ResourceManager.GetString("Path_Scripts_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBItem.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Item {
            get {
                return ResourceManager.GetString("Path_Scripts_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$MapEvents\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_MapEvents {
            get {
                return ResourceManager.GetString("Path_Scripts_MapEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBSkill.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Skill {
            get {
                return ResourceManager.GetString("Path_Scripts_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBState.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_State {
            get {
                return ResourceManager.GetString("Path_Scripts_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\$Scripts\$System\$DBUnit.nut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Scripts_Unit {
            get {
                return ResourceManager.GetString("Path_Scripts_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPGDeveloperNEXT_SQCompileResult.log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_SQCompileLog {
            get {
                return ResourceManager.GetString("Path_SQCompileLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texts\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Path_Texts {
            get {
                return ResourceManager.GetString("Path_Texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.MapData.ThisEVData.SetDirection4ToPlayer();
        ///Game.SceneMap.ShowMessage($1, $2, $3);
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //フォルダー構造一括生成用
        ///$ProjectSystem
        ///	EVTemplates
        ///	Project.json
        ///	Schedule.eds
        ///Texts
        ///	$Scripts
        ///		$MapEvents
        ///		$System
        ///			$EventHandler.nut
        ///			$Constants.nut
        ///			$Functions.nut
        ///			$SceneMainTitle.nut
        ///			$SceneMainMap.nut
        ///			$SceneSubMenu.nut
        ///			$SceneSubShop.nut
        ///			$SceneSubBattle.nut
        ///			$DBChar.nut
        ///			$DBClass.nut
        ///			$DBItem.nut
        ///			$DBSkill.nut
        ///			$DBEnemy.nut
        ///			$DBState.nut
        ///			$DBUnit.nut
        ///Databases
        ///	$UserDatabases
        ///	$Effects
        ///		$Top.nut
        ///	$Tilesets
        ///Fonts
        ///Maps
        ///Materials
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFolderDefault {
            get {
                return ResourceManager.GetString("ProjectFolderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \((?&lt;here&gt;.+\)); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Regux_ArgumentList {
            get {
                return ResourceManager.GetString("Regux_ArgumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (\(|\[).*?競合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Regux_Conflict {
            get {
                return ResourceManager.GetString("Regux_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \[\$(?&lt;ID&gt;\d+)\] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Regux_ParameterInExpression {
            get {
                return ResourceManager.GetString("Regux_ParameterInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function (?&lt;here&gt;.+\)) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Regux_SQFunction {
            get {
                return ResourceManager.GetString("Regux_SQFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;&amp;Game\.SceneMap\.MapData\.EVGetData\((.*)\)\.SelfValues\.Set\((.*),(.*)\)\) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Requx_SQSelfValueForMapTest {
            get {
                return ResourceManager.GetString("Requx_SQSelfValueForMapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (マイルストーン) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sche_MilestoneName {
            get {
                return ResourceManager.GetString("Sche_MilestoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (なし) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sche_NoneItem {
            get {
                return ResourceManager.GetString("Sche_NoneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (全員) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sche_SectionAllWorkers {
            get {
                return ResourceManager.GetString("Sche_SectionAllWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.ShowMessage($1, $2, $3);
        ///
        /////商品を登録する
        ///Game.SceneMap.ShopData.Clear();
        /////ADDITEMS
        /////ショップ画面を呼び出す
        ///Game.StartSubScene(Scene.Shop, true, true);
        ///
        ///Game.SceneMap.ShowMessage($1, $2, $4);
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Split_Argument {
            get {
                return ResourceManager.GetString("Split_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Split_ColorRGB {
            get {
                return ResourceManager.GetString("Split_ColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Split_IDNamePair {
            get {
                return ResourceManager.GetString("Split_IDNamePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Split_LongData {
            get {
                return ResourceManager.GetString("Split_LongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Split_SimpleList {
            get {
                return ResourceManager.GetString("Split_SimpleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Split_Size {
            get {
                return ResourceManager.GetString("Split_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   break; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_BlockBreak {
            get {
                return ResourceManager.GetString("SQ_BlockBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.ChangeMap($1, $2, $3, $4); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ChangeMap {
            get {
                return ResourceManager.GetString("SQ_ChangeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effect.Draw($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectDraw {
            get {
                return ResourceManager.GetString("SQ_EffectDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effect.Flash($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectFlash {
            get {
                return ResourceManager.GetString("SQ_EffectFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iFrame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectFrameCounter {
            get {
                return ResourceManager.GetString("SQ_EffectFrameCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function PlayEffect($1, $2, $3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectFunc {
            get {
                return ResourceManager.GetString("SQ_EffectFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   local Effect = Game.DB.FDBEffect.GetEffectData($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectGetData {
            get {
                return ResourceManager.GetString("SQ_EffectGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effect.LoadGraph($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectLoadGraph {
            get {
                return ResourceManager.GetString("SQ_EffectLoadGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iHandle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectPlayingHandle {
            get {
                return ResourceManager.GetString("SQ_EffectPlayingHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iTimes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectSameCounter {
            get {
                return ResourceManager.GetString("SQ_EffectSameCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effect.Shake($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectShake {
            get {
                return ResourceManager.GetString("SQ_EffectShake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effect.PlaySE($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectSound {
            get {
                return ResourceManager.GetString("SQ_EffectSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effect.WaitBreak(); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EffectWaitBreak {
            get {
                return ResourceManager.GetString("SQ_EffectWaitBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DoExtraMove($) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVExtraMoveDo {
            get {
                return ResourceManager.GetString("SQ_EVExtraMoveDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SetExtraMove($1, $2, $3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVExtraMoveSet {
            get {
                return ResourceManager.GetString("SQ_EVExtraMoveSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.ShowMessage($1, $2, $3); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVMessage {
            get {
                return ResourceManager.GetString("SQ_EVMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AddMoveTask($1, $2, $3) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVMoveSet {
            get {
                return ResourceManager.GetString("SQ_EVMoveSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.MapData.AddEVPage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVPageSetCommand {
            get {
                return ResourceManager.GetString("SQ_EVPageSetCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function EV$(%1, %2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVScript {
            get {
                return ResourceManager.GetString("SQ_EVScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pageIndex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVScript_PageIndex {
            get {
                return ResourceManager.GetString("SQ_EVScript_PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   typeID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVScript_TypeID {
            get {
                return ResourceManager.GetString("SQ_EVScript_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (!Game.SceneMap.MapData.EVGetData($1).IsNull()&amp;&amp;Game.SceneMap.MapData.EVGetData($1).SelfValues.Set($2,$3)) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVSelfValue {
            get {
                return ResourceManager.GetString("SQ_EVSelfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.MapData.SetEV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVSetCommand {
            get {
                return ResourceManager.GetString("SQ_EVSetCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function SetupMapEvents() に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_EVSetFunc {
            get {
                return ResourceManager.GetString("SQ_EVSetFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   for( に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_For {
            get {
                return ResourceManager.GetString("SQ_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_Function {
            get {
                return ResourceManager.GetString("SQ_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.DXLib.GetColor($) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_GetColor {
            get {
                return ResourceManager.GetString("SQ_GetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $ を手に入れた！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_GotTreasureMessage {
            get {
                return ResourceManager.GetString("SQ_GotTreasureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SQInclude($); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_Include {
            get {
                return ResourceManager.GetString("SQ_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.MapData.Player.MapObject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_PlayerMapObject {
            get {
                return ResourceManager.GetString("SQ_PlayerMapObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ScriptShortName {
            get {
                return ResourceManager.GetString("SQ_ScriptShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.ShopData.Add($) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ShopAddItem {
            get {
                return ResourceManager.GetString("SQ_ShopAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //################################################ The event script is as above. ################################################ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_SignUserEnd {
            get {
                return ResourceManager.GetString("SQ_SignUserEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //################################################ The event script is as follows: ################################################ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_SignUserStart {
            get {
                return ResourceManager.GetString("SQ_SignUserStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game.SceneMap.MapData.ThisEVData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ThisEVData {
            get {
                return ResourceManager.GetString("SQ_ThisEVData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_UserFlag {
            get {
                return ResourceManager.GetString("SQ_UserFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_UserInteger {
            get {
                return ResourceManager.GetString("SQ_UserInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   US に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_UserString {
            get {
                return ResourceManager.GetString("SQ_UserString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   const  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ValueConstant {
            get {
                return ResourceManager.GetString("SQ_ValueConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ValueGlobal {
            get {
                return ResourceManager.GetString("SQ_ValueGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   local  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQ_ValueLocal {
            get {
                return ResourceManager.GetString("SQ_ValueLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [CNullCheck]
        ///&lt;nodeType&gt;GameObject/Class
        ///&lt;summary&gt;Null検証クラス
        ///&lt;comment&gt;オブジェクトがnullであるかどうかを検証するクラスです。
        ///----------------------------------------
        ///[CNullCheck::IsNull]
        ///&lt;nodeType&gt;GameObject/MemberFunc
        ///&lt;summary&gt;Null検証
        ///&lt;return:bool&gt;このオブジェクトがNullである場合はTrueが返されます。
        ///&lt;comment&gt;自身のオブジェクトがNullであるかどうかを調べます。
        ///----------------------------------------
        ///[CIDNameData]
        ///&lt;nodeType&gt;GameObject/Class
        ///&lt;parent&gt;CNullCheck
        ///&lt;summary&gt;IDと名前のデータクラス
        ///&lt;comment&gt;IDと名前をセットにしたデータです。
        ///----------------------------------------
        ///[CIDNameData:: [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQCodeTree {
            get {
                return ResourceManager.GetString("SQCodeTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _add;();メタメソッド;;演算子 + に相当します。
        ///_call;();メタメソッド;;テーブル、ユーザデータ、クラスインスタンスが呼び出されたときに呼び出されます。
        ///_cmp;();メタメソッド;;比較演算子 &lt;, &gt;, &lt;=, &gt;= に相当します。
        ///_delslot;();メタメソッド;;テーブルからスロットを削除するときに呼び出されます。
        ///_div;();メタメソッド;;演算子 / に相当します。
        ///_dloned;();メタメソッド;;テーブル、ユーザデータ、クラスインスタンスが複製されたときに、複製先から呼び出されます。
        ///_get;(INDEX);メタメソッド;;インデックスが存在しないときに呼び出されます。
        ///_inherited;();メタメソッド;;クラスオブジェクトを継承するときに呼び出されます。
        ///_modulo;();メタメソッド;;演算子 % に相当します。
        ///_mul;();メタメソッド;;演算子 * に相当します。
        ///_newmember;();メタメソッド;;クラス本体で宣言される各メンバーに対して宣言時に呼び出されます。
        ///_newslot;();メタメソッド; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SquirrelKeywords {
            get {
                return ResourceManager.GetString("SquirrelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_ReplacedMark {
            get {
                return ResourceManager.GetString("Text_ReplacedMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //効果音とともにページを変更する
        ///Game.DB.FDBMaterial.Play($2, 255, 0, 0);
        ///Game.SceneMap.MapData.ThisEVData.SelfValues.Set($3, TRUE);
        ///
        /////財宝入手処理
        /////ITEM: Game.DB.VDBParty.AddItem($4A, 1);
        /////MONEY: Game.DB.VDBParty.Money += $4B;
        ///
        ///Game.SceneMap.ShowMessage(-1, &quot;&quot;, $5);
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Treasure {
            get {
                return ResourceManager.GetString("Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //財宝が入手された後かどうか
        ///return (Game.SceneMap.MapData.ThisEVData.SelfValues.Get($1).Value == TRUE);
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Treasure2ndPage {
            get {
                return ResourceManager.GetString("Treasure2ndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //鍵の所持確認
        ///if(Game.DB.VDBParty.CheckItemInParty($1)) {
        ///	//効果音とともにページを変更する
        ///	Game.DB.FDBMaterial.Play($2, 255, 0, 0);
        ///	Game.SceneMap.MapData.ThisEVData.SelfValues.Set($3, TRUE);
        ///
        ///	//財宝入手処理
        ///	//ITEM: Game.DB.VDBParty.AddItem($4A, 1);
        ///	//MONEY: Game.DB.VDBParty.Money += $4B;
        ///
        ///	Game.SceneMap.ShowMessage(-1, &quot;&quot;, $5);
        ///} else {
        ///	//鍵を持っていない場合
        ///	Game.SceneMap.ShowMessage(-1, &quot;&quot;, &quot;鍵がかかっていて開かない。&quot;);
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TreasureWithKey {
            get {
                return ResourceManager.GetString("TreasureWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap アイコン大 {
            get {
                object obj = ResourceManager.GetObject("アイコン大", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap アイコン小 {
            get {
                object obj = ResourceManager.GetObject("アイコン小", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
