//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Common_CurrentFileChanged_Confirm {
            get {
                return ((bool)(this["Common_CurrentFileChanged_Confirm"]));
            }
            set {
                this["Common_CurrentFileChanged_Confirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Common_CurrentFileChanged_AutoReload {
            get {
                return ((bool)(this["Common_CurrentFileChanged_AutoReload"]));
            }
            set {
                this["Common_CurrentFileChanged_AutoReload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Script_KeywordColor {
            get {
                return ((global::System.Drawing.Color)(this["Script_KeywordColor"]));
            }
            set {
                this["Script_KeywordColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Text_CommentColor {
            get {
                return ((global::System.Drawing.Color)(this["Text_CommentColor"]));
            }
            set {
                this["Text_CommentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Text_TextColor {
            get {
                return ((global::System.Drawing.Color)(this["Text_TextColor"]));
            }
            set {
                this["Text_TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Text_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Text_BackColor"]));
            }
            set {
                this["Text_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ＭＳ ゴシック, 9.75pt")]
        public global::System.Drawing.Font Text_Font {
            get {
                return ((global::System.Drawing.Font)(this["Text_Font"]));
            }
            set {
                this["Text_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkCyan")]
        public global::System.Drawing.Color Script_NameColor1 {
            get {
                return ((global::System.Drawing.Color)(this["Script_NameColor1"]));
            }
            set {
                this["Script_NameColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color Script_NameColor2 {
            get {
                return ((global::System.Drawing.Color)(this["Script_NameColor2"]));
            }
            set {
                this["Script_NameColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Map_NonActiveLayerTransparency {
            get {
                return ((int)(this["Map_NonActiveLayerTransparency"]));
            }
            set {
                this["Map_NonActiveLayerTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _Upgraded {
            get {
                return ((bool)(this["_Upgraded"]));
            }
            set {
                this["_Upgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size Form_MainSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_MainSize"]));
            }
            set {
                this["Form_MainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState Form_MainWndState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["Form_MainWndState"]));
            }
            set {
                this["Form_MainWndState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point Form_MainLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_MainLocation"]));
            }
            set {
                this["Form_MainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Form_2PaneImgIndices {
            get {
                return ((string)(this["Form_2PaneImgIndices"]));
            }
            set {
                this["Form_2PaneImgIndices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 9.75pt")]
        public global::System.Drawing.Font Script_Font {
            get {
                return ((global::System.Drawing.Font)(this["Script_Font"]));
            }
            set {
                this["Script_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("163, 21, 21")]
        public global::System.Drawing.Color Script_StringColor {
            get {
                return ((global::System.Drawing.Color)(this["Script_StringColor"]));
            }
            set {
                this["Script_StringColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Script_NumberColor {
            get {
                return ((global::System.Drawing.Color)(this["Script_NumberColor"]));
            }
            set {
                this["Script_NumberColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//")]
        public string Text_JumpChar {
            get {
                return ((string)(this["Text_JumpChar"]));
            }
            set {
                this["Text_JumpChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Text_UnderBar {
            get {
                return ((bool)(this["Text_UnderBar"]));
            }
            set {
                this["Text_UnderBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color Text_UnderBarColor {
            get {
                return ((global::System.Drawing.Color)(this["Text_UnderBarColor"]));
            }
            set {
                this["Text_UnderBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_TextPath {
            get {
                return ((string)(this["Last_TextPath"]));
            }
            set {
                this["Last_TextPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_MapPath {
            get {
                return ((string)(this["Last_MapPath"]));
            }
            set {
                this["Last_MapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_Chat {
            get {
                return ((string)(this["Last_Chat"]));
            }
            set {
                this["Last_Chat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Form_ScheduleSortType {
            get {
                return ((int)(this["Form_ScheduleSortType"]));
            }
            set {
                this["Form_ScheduleSortType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_ProjectPath {
            get {
                return ((string)(this["Last_ProjectPath"]));
            }
            set {
                this["Last_ProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Common_CurrentDBChanged_EditContinue {
            get {
                return ((bool)(this["Common_CurrentDBChanged_EditContinue"]));
            }
            set {
                this["Common_CurrentDBChanged_EditContinue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DB_VisibleFixedID {
            get {
                return ((bool)(this["DB_VisibleFixedID"]));
            }
            set {
                this["DB_VisibleFixedID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_UnitBackPicture {
            get {
                return ((string)(this["DB_UnitBackPicture"]));
            }
            set {
                this["DB_UnitBackPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DB_UnitScale {
            get {
                return ((int)(this["DB_UnitScale"]));
            }
            set {
                this["DB_UnitScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_EffectTargetPicture {
            get {
                return ((string)(this["DB_EffectTargetPicture"]));
            }
            set {
                this["DB_EffectTargetPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DB_EffectScale {
            get {
                return ((int)(this["DB_EffectScale"]));
            }
            set {
                this["DB_EffectScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_MapLayer {
            get {
                return ((int)(this["Last_MapLayer"]));
            }
            set {
                this["Last_MapLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Map_Scale {
            get {
                return ((int)(this["Map_Scale"]));
            }
            set {
                this["Map_Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_DB {
            get {
                return ((int)(this["Last_DB"]));
            }
            set {
                this["Last_DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_MainTabLeft {
            get {
                return ((int)(this["Last_MainTabLeft"]));
            }
            set {
                this["Last_MainTabLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_MainTabRight {
            get {
                return ((int)(this["Last_MainTabRight"]));
            }
            set {
                this["Last_MainTabRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Tkool_TileVer {
            get {
                return ((int)(this["Tkool_TileVer"]));
            }
            set {
                this["Tkool_TileVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Tkool_Interpolation {
            get {
                return ((int)(this["Tkool_Interpolation"]));
            }
            set {
                this["Tkool_Interpolation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Map_VisibleGrid {
            get {
                return ((bool)(this["Map_VisibleGrid"]));
            }
            set {
                this["Map_VisibleGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;1;2;3;4")]
        public string Map_VisibleLayerIndexList {
            get {
                return ((string)(this["Map_VisibleLayerIndexList"]));
            }
            set {
                this["Map_VisibleLayerIndexList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Map_SQEasyMode {
            get {
                return ((bool)(this["Map_SQEasyMode"]));
            }
            set {
                this["Map_SQEasyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_BattleTestPTData {
            get {
                return ((string)(this["Last_BattleTestPTData"]));
            }
            set {
                this["Last_BattleTestPTData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_MapTestValueData {
            get {
                return ((string)(this["Last_MapTestValueData"]));
            }
            set {
                this["Last_MapTestValueData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_SQTestParameter {
            get {
                return ((string)(this["Last_SQTestParameter"]));
            }
            set {
                this["Last_SQTestParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_EVTemplate_DoorSE {
            get {
                return ((string)(this["Last_EVTemplate_DoorSE"]));
            }
            set {
                this["Last_EVTemplate_DoorSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_EVTemplate_TreasureSE {
            get {
                return ((string)(this["Last_EVTemplate_TreasureSE"]));
            }
            set {
                this["Last_EVTemplate_TreasureSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Map_WaitForTest {
            get {
                return ((bool)(this["Map_WaitForTest"]));
            }
            set {
                this["Map_WaitForTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Script_FixedIDHexMode {
            get {
                return ((bool)(this["Script_FixedIDHexMode"]));
            }
            set {
                this["Script_FixedIDHexMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_DBType {
            get {
                return ((int)(this["Last_DBType"]));
            }
            set {
                this["Last_DBType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Common_NoConfirmSave {
            get {
                return ((bool)(this["Common_NoConfirmSave"]));
            }
            set {
                this["Common_NoConfirmSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Script_AutoAnalyze {
            get {
                return ((bool)(this["Script_AutoAnalyze"]));
            }
            set {
                this["Script_AutoAnalyze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_MapRandomFloorTile {
            get {
                return ((string)(this["Last_MapRandomFloorTile"]));
            }
            set {
                this["Last_MapRandomFloorTile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_MapRandomCeilTile {
            get {
                return ((string)(this["Last_MapRandomCeilTile"]));
            }
            set {
                this["Last_MapRandomCeilTile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_MapRandomWallTile {
            get {
                return ((string)(this["Last_MapRandomWallTile"]));
            }
            set {
                this["Last_MapRandomWallTile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_TextSearchRange {
            get {
                return ((int)(this["Last_TextSearchRange"]));
            }
            set {
                this["Last_TextSearchRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Last_TextSearchRegux {
            get {
                return ((bool)(this["Last_TextSearchRegux"]));
            }
            set {
                this["Last_TextSearchRegux"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Last_TextSearchCase {
            get {
                return ((bool)(this["Last_TextSearchCase"]));
            }
            set {
                this["Last_TextSearchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Tkool_WalkVer {
            get {
                return ((int)(this["Tkool_WalkVer"]));
            }
            set {
                this["Tkool_WalkVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState Help_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["Help_WindowState"]));
            }
            set {
                this["Help_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 500")]
        public global::System.Drawing.Size Help_WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["Help_WindowSize"]));
            }
            set {
                this["Help_WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point Help_WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["Help_WindowLocation"]));
            }
            set {
                this["Help_WindowLocation"] = value;
            }
        }
    }
}
